// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Plannyt.Api.Infrastructure.Persistence;

#nullable disable

namespace Plannyt.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlannytDbContext))]
    [Migration("20260728162223_RequireDocumentContext")]
    partial class RequireDocumentContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plannyt.Api.Modules.Access.Domain.AccessInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IntendedEventRole")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("intended_event_role");

                    b.Property<string>("IntendedOrganizationRole")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("intended_organization_role");

                    b.Property<string>("InvitationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("invitation_type");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<string>("NormalizedTargetEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_target_email");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TargetEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("target_email");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_access_invitations");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("ix_access_invitations_invited_by");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_access_invitations_token_hash");

                    b.HasIndex("OrganizationId", "EventId")
                        .HasDatabaseName("ix_access_invitations_organization_id_event_id");

                    b.HasIndex("OrganizationId", "NormalizedTargetEmail", "ExpiresAt")
                        .HasDatabaseName("ix_access_invitations_organization_id_normalized_target_email_");

                    b.ToTable("access_invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_access_invitations_completion", "accepted_at IS NULL OR revoked_at IS NULL");

                            t.HasCheckConstraint("ck_access_invitations_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_access_invitations_type", "(invitation_type = 'OrganizationMembership' AND event_id IS NULL AND intended_organization_role IS NOT NULL AND intended_event_role IS NULL) OR (invitation_type = 'EventAccess' AND event_id IS NOT NULL AND intended_organization_role IS NULL AND intended_event_role IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Access.Domain.EventAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("BaseRole")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("base_role");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_event_accesses");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_event_accesses_organization_id_id");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("ix_event_accesses_invited_by");

                    b.HasIndex("UserAccountId")
                        .HasDatabaseName("ix_event_accesses_user_account_id");

                    b.HasIndex("OrganizationId", "EventId", "UserAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_accesses_organization_id_event_id_user_account_id")
                        .HasFilter("status <> 'Revoked' AND revoked_at IS NULL");

                    b.ToTable("event_accesses", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_accesses_dates", "expires_at IS NULL OR expires_at > starts_at");

                            t.HasCheckConstraint("ck_event_accesses_revoked_at", "(status = 'Revoked' AND revoked_at IS NOT NULL) OR (status <> 'Revoked' AND revoked_at IS NULL)");
                        });
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Audit.Domain.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_entries_actor_user_id");

                    b.HasIndex("OrganizationId", "EventId")
                        .HasDatabaseName("ix_audit_entries_organization_id_event_id");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_organization_id_occurred_at");

                    b.HasIndex("OrganizationId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entries_organization_id_entity_type_entity_id");

                    b.ToTable("audit_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_entries_event_context", "event_id IS NULL OR organization_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Crm.Domain.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("client_type");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_clients_organization_id_id");

                    b.HasIndex("OrganizationId", "DisplayName")
                        .HasDatabaseName("ix_clients_organization_id_display_name");

                    b.HasIndex("OrganizationId", "PersonId")
                        .HasDatabaseName("ix_clients_organization_id_person_id");

                    b.ToTable("clients", null, t =>
                        {
                            t.HasCheckConstraint("ck_clients_type", "(client_type = 'Person' AND person_id IS NOT NULL AND company_name IS NULL) OR (client_type = 'Company' AND person_id IS NULL AND company_name IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Crm.Domain.ClientContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ContactRole")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("contact_role");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_client_contacts");

                    b.HasIndex("OrganizationId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_client_contacts_organization_id_client_id")
                        .HasFilter("is_primary");

                    b.HasIndex("OrganizationId", "PersonId")
                        .HasDatabaseName("ix_client_contacts_organization_id_person_id");

                    b.ToTable("client_contacts", (string)null);
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Documents.Domain.BasicDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("document_type");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("storage_provider");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_basic_documents");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_basic_documents_organization_id_id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_basic_documents_storage_key");

                    b.HasIndex("UploadedBy")
                        .HasDatabaseName("ix_basic_documents_uploaded_by");

                    b.HasIndex("OrganizationId", "ClientId")
                        .HasDatabaseName("ix_basic_documents_organization_id_client_id");

                    b.HasIndex("OrganizationId", "EventId", "Visibility", "DeletedAt")
                        .HasDatabaseName("ix_basic_documents_organization_id_event_id_visibility_deleted");

                    b.ToTable("basic_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_basic_documents_context", "event_id IS NOT NULL OR client_id IS NOT NULL");

                            t.HasCheckConstraint("ck_basic_documents_size", "size_bytes > 0 AND size_bytes <= 10485760");
                        });
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Events.Domain.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_time");

                    b.Property<int?>("EstimatedGuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_guest_count");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("event_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SharedDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("shared_description");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StatusBeforeSuspension")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status_before_suspension");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_events_organization_id_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_events_created_by");

                    b.HasIndex("OrganizationId", "StartDateTime")
                        .HasDatabaseName("ix_events_organization_id_start_date_time");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_events_organization_id_status");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_archived_at", "(status = 'Archived' AND archived_at IS NOT NULL) OR (status <> 'Archived' AND archived_at IS NULL)");

                            t.HasCheckConstraint("ck_events_dates", "end_date_time IS NULL OR end_date_time >= start_date_time");

                            t.HasCheckConstraint("ck_events_guest_count", "estimated_guest_count IS NULL OR estimated_guest_count >= 0");
                        });
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Events.Domain.EventClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("HasTransferAuthority")
                        .HasColumnType("boolean")
                        .HasColumnName("has_transfer_authority");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("relationship_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_event_clients");

                    b.HasIndex("OrganizationId", "ClientId")
                        .HasDatabaseName("ix_event_clients_organization_id_client_id");

                    b.HasIndex("OrganizationId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_event_clients_organization_id_event_id")
                        .HasFilter("is_primary");

                    b.HasIndex("OrganizationId", "EventId", "ClientId", "RelationshipType")
                        .IsUnique()
                        .HasDatabaseName("ix_event_clients_organization_id_event_id_client_id_relationsh");

                    b.ToTable("event_clients", (string)null);
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Events.Domain.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsVisibleToClient")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible_to_client");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("participant_type");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("SharedDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("shared_description");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_event_participants");

                    b.HasIndex("OrganizationId", "PersonId")
                        .HasDatabaseName("ix_event_participants_organization_id_person_id");

                    b.HasIndex("OrganizationId", "EventId", "DisplayOrder")
                        .HasDatabaseName("ix_event_participants_organization_id_event_id_display_order");

                    b.ToTable("event_participants", (string)null);
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Events.Domain.EventStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("new_status");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_event_status_history");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("ix_event_status_history_changed_by");

                    b.HasIndex("OrganizationId", "EventId", "ChangedAt")
                        .HasDatabaseName("ix_event_status_history_organization_id_event_id_changed_at");

                    b.ToTable("event_status_history", (string)null);
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Identity.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<int>("SecurityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("security_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_normalized_email");

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Identity.Domain.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_persistent");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("LastUsedIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_used_ip");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("SecurityVersionAtCreation")
                        .HasColumnType("integer")
                        .HasColumnName("security_version_at_creation");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_refresh_token_hash");

                    b.HasIndex("ReplacedBySessionId")
                        .HasDatabaseName("ix_user_sessions_replaced_by_session_id");

                    b.HasIndex("UserAccountId", "RevokedAt")
                        .HasDatabaseName("ix_user_sessions_user_account_id_revoked_at");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Organizations.Domain.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("OrganizationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("organization_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Organizations.Domain.OrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseRole")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("base_role");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_memberships");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_organization_memberships_organization_id_id");

                    b.HasIndex("UserAccountId")
                        .HasDatabaseName("ix_organization_memberships_user_account_id");

                    b.HasIndex("OrganizationId", "PersonId")
                        .HasDatabaseName("ix_organization_memberships_organization_id_person_id");

                    b.HasIndex("OrganizationId", "UserAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_memberships_organization_id_user_account_id")
                        .HasFilter("status = 'Active'");

                    b.ToTable("organization_memberships", (string)null);
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Organizations.Domain.PermissionGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("effect");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("OrganizationMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_membership_id");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("permission");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_account_id");

                    b.HasKey("Id")
                        .HasName("pk_permission_grants");

                    b.HasIndex("UserAccountId")
                        .HasDatabaseName("ix_permission_grants_user_account_id");

                    b.HasIndex("OrganizationId", "EventId")
                        .HasDatabaseName("ix_permission_grants_organization_id_event_id");

                    b.HasIndex("OrganizationId", "OrganizationMembershipId", "Permission", "EventId")
                        .HasDatabaseName("ix_permission_grants_organization_id_organization_membership_i");

                    b.HasIndex("OrganizationId", "UserAccountId", "Permission", "EventId")
                        .HasDatabaseName("ix_permission_grants_organization_id_user_account_id_permissio");

                    b.ToTable("permission_grants", null, t =>
                        {
                            t.HasCheckConstraint("ck_permission_grants_scope", "(scope = 'Organization' AND event_id IS NULL) OR (scope = 'Event' AND event_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_permission_grants_subject", "(user_account_id IS NOT NULL AND organization_membership_id IS NULL) OR (user_account_id IS NULL AND organization_membership_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Organizations.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("LinkedUserAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_user_account_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("preferred_language");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_people_organization_id_id");

                    b.HasIndex("LinkedUserAccountId")
                        .HasDatabaseName("ix_people_linked_user_account_id");

                    b.HasIndex("OrganizationId", "LinkedUserAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_people_organization_id_linked_user_account_id")
                        .HasFilter("linked_user_account_id IS NOT NULL AND archived_at IS NULL");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Access.Domain.AccessInvitation", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_invitations_user_accounts_invited_by");

                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_invitations_organizations_organization_id");

                    b.HasOne("Plannyt.Api.Modules.Events.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EventId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_invitations_events_organization_id_event_id");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Access.Domain.EventAccess", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_accesses_user_accounts_invited_by");

                    b.HasOne("Plannyt.Api.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_accesses_user_accounts_user_account_id");

                    b.HasOne("Plannyt.Api.Modules.Events.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EventId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_accesses_events_organization_id_event_id");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Audit.Domain.AuditEntry", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_entries_user_accounts_actor_user_id");

                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_entries_organizations_organization_id");

                    b.HasOne("Plannyt.Api.Modules.Events.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EventId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_entries_events_organization_id_event_id");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Crm.Domain.Client", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clients_organizations_organization_id");

                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PersonId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clients_people_organization_id_person_id");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Crm.Domain.ClientContact", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Crm.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClientId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_contacts_clients_organization_id_client_id");

                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PersonId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_client_contacts_people_organization_id_person_id");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Documents.Domain.BasicDocument", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_basic_documents_organizations_organization_id");

                    b.HasOne("Plannyt.Api.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_basic_documents_user_accounts_uploaded_by");

                    b.HasOne("Plannyt.Api.Modules.Crm.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClientId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_basic_documents_clients_organization_id_client_id");

                    b.HasOne("Plannyt.Api.Modules.Events.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EventId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_basic_documents_events_organization_id_event_id");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Events.Domain.Event", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_user_accounts_created_by");

                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_organizations_organization_id");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Events.Domain.EventClient", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Crm.Domain.Client", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ClientId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_clients_clients_organization_id_client_id");

                    b.HasOne("Plannyt.Api.Modules.Events.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EventId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_clients_events_organization_id_event_id");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Events.Domain.EventParticipant", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Events.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EventId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_participants_events_organization_id_event_id");

                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PersonId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_participants_people_organization_id_person_id");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Events.Domain.EventStatusHistory", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_status_history_user_accounts_changed_by");

                    b.HasOne("Plannyt.Api.Modules.Events.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EventId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_status_history_events_organization_id_event_id");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Identity.Domain.UserSession", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Identity.Domain.UserSession", null)
                        .WithMany()
                        .HasForeignKey("ReplacedBySessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_sessions_user_sessions_replaced_by_session_id");

                    b.HasOne("Plannyt.Api.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_user_accounts_user_account_id");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Organizations.Domain.OrganizationMembership", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_organizations_organization_id");

                    b.HasOne("Plannyt.Api.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_user_accounts_user_account_id");

                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PersonId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_people_organization_id_person_id");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Organizations.Domain.PermissionGrant", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permission_grants_organizations_organization_id");

                    b.HasOne("Plannyt.Api.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_permission_grants_user_accounts_user_account_id");

                    b.HasOne("Plannyt.Api.Modules.Events.Domain.Event", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EventId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_permission_grants_events_organization_id_event_id");

                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.OrganizationMembership", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OrganizationMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_permission_grants_organization_memberships_organization_id_");
                });

            modelBuilder.Entity("Plannyt.Api.Modules.Organizations.Domain.Person", b =>
                {
                    b.HasOne("Plannyt.Api.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("LinkedUserAccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_people_user_accounts_linked_user_account_id");

                    b.HasOne("Plannyt.Api.Modules.Organizations.Domain.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_people_organizations_organization_id");
                });
#pragma warning restore 612, 618
        }
    }
}
