using Plannyt.Api.Modules.Access.Domain;
using Plannyt.Api.Modules.Organizations.Domain;

namespace Plannyt.Api.Modules.Organizations.Authorization;

public static class RolePermissionCatalog
{
    private static readonly IReadOnlyDictionary<OrganizationRole, IReadOnlySet<string>>
        OrganizationPermissions =
            new Dictionary<OrganizationRole, IReadOnlySet<string>>
            {
                [OrganizationRole.Owner] = Copy(Permissions.All),
                [OrganizationRole.OrganizationAdmin] = Copy(Permissions.All),
                [OrganizationRole.Planner] = Set(
                    Permissions.OrganizationView,
                    Permissions.OrganizationMembersView,
                    Permissions.ClientsView,
                    Permissions.ClientsCreate,
                    Permissions.ClientsUpdate,
                    Permissions.ClientsArchive,
                    Permissions.ClientsPrivateNotesView,
                    Permissions.ClientsPrivateNotesManage,
                    Permissions.ProspectsView,
                    Permissions.ProspectsCreate,
                    Permissions.ProspectsUpdate,
                    Permissions.ProspectsAssign,
                    Permissions.ProspectsChangeStatus,
                    Permissions.ProspectsArchive,
                    Permissions.ProspectsPrivateNotesView,
                    Permissions.ProspectsPrivateNotesManage,
                    Permissions.CatalogView,
                    Permissions.CatalogManage,
                    Permissions.PackagesView,
                    Permissions.PackagesManage,
                    Permissions.CouponsView,
                    Permissions.CouponsManage,
                    Permissions.ProposalsView,
                    Permissions.ProposalsCreate,
                    Permissions.ProposalsUpdateDraft,
                    Permissions.ProposalsPublish,
                    Permissions.ProposalsSend,
                    Permissions.ProposalsCancel,
                    Permissions.ProposalsViewInternal,
                    Permissions.ProposalsManageComments,
                    Permissions.ProposalsConvertClient,
                    Permissions.ContractTemplatesView,
                    Permissions.ContractTemplatesManage,
                    Permissions.ContractsView,
                    Permissions.ContractsCreate,
                    Permissions.ContractsUpdateDraft,
                    Permissions.ContractsPublish,
                    Permissions.ContractsSend,
                    Permissions.ContractsCancel,
                    Permissions.ContractsUploadExternal,
                    Permissions.ContractsValidateExternal,
                    Permissions.ContractsViewInternal,
                    Permissions.SignaturesView,
                    Permissions.SignaturesManageSigners,
                    Permissions.SignaturesCreateRequest,
                    Permissions.SignaturesRevokeRequest,
                    Permissions.SignaturesCountersign,
                    Permissions.SignaturesViewEvidence,
                    Permissions.PaymentPlansView,
                    Permissions.PaymentPlansCreate,
                    Permissions.PaymentPlansUpdateDraft,
                    Permissions.PaymentPlansActivate,
                    Permissions.PaymentPlansCancel,
                    Permissions.PaymentsView,
                    Permissions.PaymentsCreate,
                    Permissions.PaymentsApprove,
                    Permissions.PaymentsReject,
                    Permissions.PaymentsCancel,
                    Permissions.PaymentsRefund,
                    Permissions.PaymentsViewInternal,
                    Permissions.EventsView,
                    Permissions.EventsCreate,
                    Permissions.EventsUpdate,
                    Permissions.EventsArchive,
                    Permissions.EventsMembersView,
                    Permissions.EventsMembersInvite,
                    Permissions.EventsMembersUpdate,
                    Permissions.EventsMembersRevoke,
                    Permissions.EventsInternalDataView,
                    Permissions.EventsSharedDataView,
                    Permissions.EventsConfirm,
                    Permissions.ParticipantsView,
                    Permissions.ParticipantsManage,
                    Permissions.GuestsView,
                    Permissions.GuestsCreate,
                    Permissions.GuestsUpdate,
                    Permissions.GuestsArchive,
                    Permissions.GuestsImport,
                    Permissions.GuestsExport,
                    Permissions.GuestsViewPrivate,
                    Permissions.GuestsManageTags,
                    Permissions.InvitationGroupsView,
                    Permissions.InvitationGroupsCreate,
                    Permissions.InvitationGroupsUpdate,
                    Permissions.InvitationGroupsArchive,
                    Permissions.InvitationGroupsManageCapacity,
                    Permissions.InvitationGroupsViewPrivate,
                    Permissions.InvitationDesignsView,
                    Permissions.InvitationDesignsCreate,
                    Permissions.InvitationDesignsUpdateDraft,
                    Permissions.InvitationDesignsSubmitReview,
                    Permissions.InvitationDesignsApprove,
                    Permissions.InvitationDesignsPublish,
                    Permissions.InvitationDesignsArchive,
                    Permissions.InvitationDesignsManageTemplates,
                    Permissions.GuestLinksView,
                    Permissions.GuestLinksGenerate,
                    Permissions.GuestLinksRegenerate,
                    Permissions.GuestLinksRevoke,
                    Permissions.GuestLinksMarkShared,
                    Permissions.DocumentsViewShared,
                    Permissions.DocumentsUploadShared,
                    Permissions.DocumentsViewInternal,
                    Permissions.DocumentsUploadInternal,
                    Permissions.DocumentsDelete,
                    Permissions.RsvpSettingsView,
                    Permissions.RsvpSettingsManage,
                    Permissions.RsvpSettingsPublish,
                    Permissions.RsvpSettingsOpenClose,
                    Permissions.RsvpFormsView,
                    Permissions.RsvpFormsCreate,
                    Permissions.RsvpFormsUpdateDraft,
                    Permissions.RsvpFormsSubmitReview,
                    Permissions.RsvpFormsApprove,
                    Permissions.RsvpFormsPublish,
                    Permissions.RsvpResponsesView,
                    Permissions.RsvpResponsesCreateManual,
                    Permissions.RsvpResponsesCorrect,
                    Permissions.RsvpResponsesReopen,
                    Permissions.RsvpResponsesExport,
                    Permissions.RsvpResponsesViewHistory,
                    Permissions.EventMenusView,
                    Permissions.EventMenusManage,
                    Permissions.EventMenusExport,
                    Permissions.GuestTravelView,
                    Permissions.GuestTravelManage,
                    Permissions.GuestTravelExport,
                    Permissions.GuestRemindersView,
                    Permissions.GuestRemindersManage,
                    Permissions.GuestRemindersMarkSent,
                    Permissions.AuditView),
                [OrganizationRole.Coordinator] = Set(
                    Permissions.OrganizationView,
                    Permissions.OrganizationMembersView,
                    Permissions.ClientsView,
                    Permissions.ClientsUpdate,
                    Permissions.ClientsPrivateNotesView,
                    Permissions.ClientsPrivateNotesManage,
                    Permissions.ProspectsView,
                    Permissions.ProspectsUpdate,
                    Permissions.ProspectsChangeStatus,
                    Permissions.ProspectsPrivateNotesView,
                    Permissions.ProspectsPrivateNotesManage,
                    Permissions.CatalogView,
                    Permissions.PackagesView,
                    Permissions.CouponsView,
                    Permissions.ProposalsView,
                    Permissions.ProposalsUpdateDraft,
                    Permissions.ProposalsManageComments,
                    Permissions.ContractTemplatesView,
                    Permissions.ContractsView,
                    Permissions.ContractsCreate,
                    Permissions.ContractsUpdateDraft,
                    Permissions.SignaturesView,
                    Permissions.SignaturesManageSigners,
                    Permissions.PaymentPlansView,
                    Permissions.PaymentPlansCreate,
                    Permissions.PaymentPlansUpdateDraft,
                    Permissions.PaymentsView,
                    Permissions.PaymentsCreate,
                    Permissions.EventsView,
                    Permissions.EventsUpdate,
                    Permissions.EventsMembersView,
                    Permissions.EventsMembersInvite,
                    Permissions.EventsInternalDataView,
                    Permissions.EventsSharedDataView,
                    Permissions.ParticipantsView,
                    Permissions.ParticipantsManage,
                    Permissions.GuestsView,
                    Permissions.GuestsCreate,
                    Permissions.GuestsUpdate,
                    Permissions.GuestsArchive,
                    Permissions.GuestsImport,
                    Permissions.GuestsExport,
                    Permissions.GuestsViewPrivate,
                    Permissions.GuestsManageTags,
                    Permissions.InvitationGroupsView,
                    Permissions.InvitationGroupsCreate,
                    Permissions.InvitationGroupsUpdate,
                    Permissions.InvitationGroupsArchive,
                    Permissions.InvitationGroupsManageCapacity,
                    Permissions.InvitationGroupsViewPrivate,
                    Permissions.InvitationDesignsView,
                    Permissions.InvitationDesignsCreate,
                    Permissions.InvitationDesignsUpdateDraft,
                    Permissions.InvitationDesignsSubmitReview,
                    Permissions.InvitationDesignsApprove,
                    Permissions.InvitationDesignsPublish,
                    Permissions.InvitationDesignsArchive,
                    Permissions.GuestLinksView,
                    Permissions.GuestLinksGenerate,
                    Permissions.GuestLinksRegenerate,
                    Permissions.GuestLinksRevoke,
                    Permissions.GuestLinksMarkShared,
                    Permissions.DocumentsViewShared,
                    Permissions.DocumentsUploadShared,
                    Permissions.DocumentsViewInternal,
                    Permissions.DocumentsUploadInternal,
                    Permissions.DocumentsDelete,
                    Permissions.RsvpResponsesView,
                    Permissions.RsvpResponsesCreateManual,
                    Permissions.RsvpResponsesViewHistory,
                    Permissions.EventMenusView,
                    Permissions.EventMenusManage,
                    Permissions.GuestTravelView,
                    Permissions.GuestTravelManage,
                    Permissions.GuestRemindersView,
                    Permissions.GuestRemindersManage,
                    Permissions.GuestRemindersMarkSent),
                [OrganizationRole.Assistant] = Set(
                    Permissions.OrganizationView,
                    Permissions.OrganizationMembersView,
                    Permissions.ClientsView,
                    Permissions.ProspectsView,
                    Permissions.CatalogView,
                    Permissions.PackagesView,
                    Permissions.ProposalsView,
                    Permissions.EventsView,
                    Permissions.EventsUpdate,
                    Permissions.EventsMembersView,
                    Permissions.EventsInternalDataView,
                    Permissions.EventsSharedDataView,
                    Permissions.ParticipantsView,
                    Permissions.ParticipantsManage,
                    Permissions.GuestsView,
                    Permissions.GuestsCreate,
                    Permissions.GuestsUpdate,
                    Permissions.GuestsImport,
                    Permissions.InvitationGroupsView,
                    Permissions.InvitationGroupsCreate,
                    Permissions.InvitationGroupsUpdate,
                    Permissions.InvitationDesignsView,
                    Permissions.InvitationDesignsCreate,
                    Permissions.InvitationDesignsUpdateDraft,
                    Permissions.InvitationDesignsSubmitReview,
                    Permissions.GuestLinksView,
                    Permissions.GuestLinksGenerate,
                    Permissions.GuestLinksMarkShared,
                    Permissions.DocumentsViewShared,
                    Permissions.DocumentsUploadShared,
                    Permissions.DocumentsViewInternal,
                    Permissions.DocumentsUploadInternal),
                [OrganizationRole.Commercial] = Set(
                    Permissions.OrganizationView,
                    Permissions.ClientsView,
                    Permissions.ClientsCreate,
                    Permissions.ClientsUpdate,
                    Permissions.ClientsArchive,
                    Permissions.ClientsPrivateNotesView,
                    Permissions.ClientsPrivateNotesManage,
                    Permissions.ProspectsView,
                    Permissions.ProspectsCreate,
                    Permissions.ProspectsUpdate,
                    Permissions.ProspectsAssign,
                    Permissions.ProspectsChangeStatus,
                    Permissions.ProspectsArchive,
                    Permissions.ProspectsPrivateNotesView,
                    Permissions.ProspectsPrivateNotesManage,
                    Permissions.CatalogView,
                    Permissions.PackagesView,
                    Permissions.CouponsView,
                    Permissions.ProposalsView,
                    Permissions.ProposalsCreate,
                    Permissions.ProposalsUpdateDraft,
                    Permissions.ProposalsPublish,
                    Permissions.ProposalsSend,
                    Permissions.ProposalsCancel,
                    Permissions.ProposalsViewInternal,
                    Permissions.ProposalsManageComments,
                    Permissions.ProposalsConvertClient,
                    Permissions.ContractTemplatesView,
                    Permissions.ContractsView,
                    Permissions.ContractsCreate,
                    Permissions.ContractsUpdateDraft,
                    Permissions.ContractsPublish,
                    Permissions.ContractsSend,
                    Permissions.SignaturesView,
                    Permissions.SignaturesManageSigners,
                    Permissions.SignaturesCreateRequest,
                    Permissions.EventsView,
                    Permissions.EventsCreate,
                    Permissions.EventsSharedDataView,
                    Permissions.ParticipantsView,
                    Permissions.DocumentsViewShared,
                    Permissions.DocumentsUploadShared),
                [OrganizationRole.Finance] = Set(
                    Permissions.OrganizationView,
                    Permissions.ClientsView,
                    Permissions.CatalogView,
                    Permissions.PackagesView,
                    Permissions.CouponsView,
                    Permissions.ProposalsView,
                    Permissions.ProposalsViewInternal,
                    Permissions.ContractsView,
                    Permissions.ContractsViewInternal,
                    Permissions.SignaturesView,
                    Permissions.SignaturesViewEvidence,
                    Permissions.PaymentPlansView,
                    Permissions.PaymentPlansCreate,
                    Permissions.PaymentPlansUpdateDraft,
                    Permissions.PaymentPlansActivate,
                    Permissions.PaymentPlansCancel,
                    Permissions.PaymentsView,
                    Permissions.PaymentsCreate,
                    Permissions.PaymentsApprove,
                    Permissions.PaymentsReject,
                    Permissions.PaymentsCancel,
                    Permissions.PaymentsRefund,
                    Permissions.PaymentsViewInternal,
                    Permissions.EventsView,
                    Permissions.EventsInternalDataView,
                    Permissions.EventsSharedDataView,
                    Permissions.ParticipantsView,
                    Permissions.DocumentsViewShared,
                    Permissions.DocumentsViewInternal,
                    Permissions.AuditView)
            };

    private static readonly IReadOnlySet<string> ClientPortalViewPermissions = Set(
        Permissions.EventsView,
        Permissions.EventsSharedDataView,
        Permissions.ParticipantsView,
        Permissions.GuestsView,
        Permissions.InvitationGroupsView,
        Permissions.InvitationDesignsView,
        Permissions.GuestLinksView,
        Permissions.RsvpResponsesView,
        Permissions.DocumentsViewShared,
        Permissions.ContractsView,
        Permissions.SignaturesView,
        Permissions.PaymentPlansView,
        Permissions.PaymentsView);

    private static readonly IReadOnlySet<string> ClientGuestManagementPermissions = Set(
        Permissions.GuestsCreate,
        Permissions.GuestsUpdate,
        Permissions.GuestsArchive,
        Permissions.GuestsImport,
        Permissions.GuestsManageTags,
        Permissions.InvitationGroupsCreate,
        Permissions.InvitationGroupsUpdate,
        Permissions.InvitationGroupsArchive,
        Permissions.InvitationGroupsManageCapacity,
        Permissions.GuestLinksMarkShared,
        Permissions.RsvpResponsesCreateManual,
        Permissions.RsvpResponsesCorrect);

    private static readonly IReadOnlySet<string> ClientInvitationCollaborationPermissions = Set(
        Permissions.InvitationDesignsUpdateDraft,
        Permissions.InvitationDesignsSubmitReview);

    private static readonly IReadOnlyDictionary<EventAccessRole, IReadOnlySet<string>>
        EventAccessPermissions =
            new Dictionary<EventAccessRole, IReadOnlySet<string>>
            {
                [EventAccessRole.ClientAuthority] = Union(
                    ClientPortalViewPermissions,
                    ClientGuestManagementPermissions,
                    ClientInvitationCollaborationPermissions,
                    Set(
                        Permissions.InvitationDesignsApprove,
                        Permissions.PaymentsCreate)),
                [EventAccessRole.ClientPrimary] = Union(
                    ClientPortalViewPermissions,
                    ClientGuestManagementPermissions,
                    ClientInvitationCollaborationPermissions,
                    Set(
                        Permissions.InvitationDesignsApprove,
                        Permissions.PaymentsCreate)),
                [EventAccessRole.ClientCollaborator] = Union(
                    ClientPortalViewPermissions,
                    ClientGuestManagementPermissions,
                    ClientInvitationCollaborationPermissions),
                [EventAccessRole.ClientGuestManager] = Union(
                    ClientPortalViewPermissions,
                    ClientGuestManagementPermissions),
                [EventAccessRole.ClientPayer] = Union(
                    ClientPortalViewPermissions,
                    Set(Permissions.PaymentsCreate)),
                [EventAccessRole.ClientApprover] = Union(
                    ClientPortalViewPermissions,
                    Set(Permissions.InvitationDesignsApprove)),
                [EventAccessRole.ClientViewer] = Copy(
                    ClientPortalViewPermissions)
            };

    public static IReadOnlySet<string> GetFor(OrganizationRole role) =>
        OrganizationPermissions[role];

    public static IReadOnlySet<string> GetFor(EventAccessRole role)
        => EventAccessPermissions[role];

    private static IReadOnlySet<string> Set(params string[] permissions) =>
        new HashSet<string>(permissions, StringComparer.Ordinal);

    private static IReadOnlySet<string> Copy(IEnumerable<string> permissions) =>
        new HashSet<string>(permissions, StringComparer.Ordinal);

    private static IReadOnlySet<string> Union(
        params IEnumerable<string>[] permissionGroups) =>
        new HashSet<string>(
            permissionGroups.SelectMany(permissions => permissions),
            StringComparer.Ordinal);
}
